apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.annie.name }}
type: Opaque
data:
  username: {{ .Values.secret.username }}
  password: <base64-encoded-password>
  database: <base64-encoded-database>
