apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.annie.name }}-svc
    {{- include "espresso-shop-reviews.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "espresso-shop-reviews.selectorLabels" . | nindent 4 }}
