---
# Source: espresso-shop-web/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espresso-sa
  # labels:
  #   version: v1
---
# Source: espresso-shop-web/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: espresso-shop-web
type: Opaque
data:
  username: cmVkaXM=
  password: bXktcmVkaXMtc2hvcC1lc3ByZXNzbw==
---
# Source: espresso-shop-web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: espresso-web-svc
  #labels:
    #version: v1
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    version: v1
    app: espresso-w1
---
# Source: espresso-shop-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-web
  labels:
    # version: v1
    app: espresso-w1
spec:
  selector:
    matchLabels:
      version: v1
      app: espresso-w1
  template:
    metadata:
      labels:
        version: v1
        app: espresso-w1
    spec:
      serviceAccountName: espresso-sa
      securityContext:
        {}
      containers:
        - name: espresso-shop-web
          securityContext:
            {}
          image: "devopseasylearning/espresso-shop-web-annie:latest"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: espresso-shop-web 
          env: 
            - name: ProductCatalogUrl
              value: http://espresso-shop-product-catalog-svc:8091
            - name: ReviewsUrl
              value: http://espresso-shop-reviews-svc:8092  
          ports:
            - name: http
              containerPort: 80
              protocol: TCP    
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: espresso-shop-web/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: espresso-shop-web
  #labels:
    # version: v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: espresso-shop-web
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
